### ISSUE TITLE
Server return error 500 after several Hails

### ISSUE THREAD

**Issue by supmob1** [openmaraude/APITaxi#227]
1 - I post some dummy hails through Swagger to test the operator endpoint 
sample hails :
{
  "data": [
   {
  "customer_address": "63,Rue des Rancy,Rhône",
  "customer_id": "mob1Taxi-0-c62f3bce-146d-4366-ab9d-8c747b105755",
  "customer_lat": "45.756501",
  "customer_lon": "4.856979",
  "customer_phone_number": "+33 662265",
  "operateur": "mob1taxi",
  "taxi_id": "03013dbb-5df2-4f51-8876-06028447aaef"
}
  ]
}
1-bis - We let the Hails in mode "received_by_the_operator" and continue to send the same
again and again to test some concurrency scenario.

2- It works well, let's say 5-6 times, then it fallback to an error 500 page
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
on all API : we cannot set taxi back to "free" with PUT, and same issue on GET /hails/hailsid

3 - It is quite impossible for us, to continue developing and testing the complete system (search engine and operator got the same issues), because it blocks like this the full day, and we wait the day after to start re-work on the Hails Api. We loose a lot of time.

I know that you plan migrating the old dev server to new one, so we will stop our development until
the new server is available or find a way to fix this Error 500.

**Comment by odtvince** [comment]
We are aware of the problem you encounter and are working on a fix.
 
In the mean time, jut send me an email when you encounter the 500 errors, I can unblock it.

**Comment by odtvince** [comment]
A temporary fix has been deployed.

We will work on a proper fix next week, but you should not encounter those 500 anymore.

**Comment by odtvince** [comment]
Sorta solved: only happens with apache/mod_wsgi.
The recommended deployment platform is now nginx based.
